### Car Controller Testing

@url = http://localhost:8080/api/ride_on/car

### Create Car
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyaWRlLW9uIiwic3ViIjoibGtpbUBkZXYtMTAuY29tIiwidXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjc1NDAyMTk2fQ.HND8Mmr-xkFW1QqzUgNX_wtpFYzrdHgt7p7sUnPEJD0

{
    "insurance": true,
    "registration": true,
    "make": "Chevy",
    "model": "Tahoe",
    "year": "2022",
    "color": "black",
    "licensePlate": "k1lla",
    "trips": [],
    "userId": 1
}