### Car Controller Testing

@url = http://localhost:8080/api/ride_on/car

### Create Car
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyaWRlLW9uIiwic3ViIjoiTWhlaW5lQGRldi0xMC5jb20iLCJ1c2VyX2lkIjoyLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2NzU3MDI2ODB9.QVSt_6D-DLXVTCZI_4yfbNOyy3l3Vj9V6loZl2acAhk

{
    "insurance": true,
    "registration": true,
    "make": "Chevy",
    "model": "Tahoe",
    "year": "2022",
    "color": "black",
    "licensePlate": "k1lla",
    "trips": [],
    "userId": 1
}