### Rider Controller

@url = http://localhost:8080/api/ride_on/rider

### Create Rider
POST {{url}}/2/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyaWRlLW9uIiwic3ViIjoiTWhlaW5lQGRldi0xMC5jb20iLCJ1c2VyX2lkIjoyLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2NzU0MDI3NTJ9.RZnfMgZazCrO2_tjxLE8FvvzR-KHaPvx2xVqAJ2K440

{
    "totalCost": 150,
    "paymentConfirmation": true,
    "userId": 1,
    "tripId": 1
}

### Find Rider By Trip ID
GET {{url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyaWRlLW9uIiwic3ViIjoibGtpbUBkZXYtMTAuY29tIiwidXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjc1NDM4NTYwfQ.trTZ7IhyNM2wUh9Wupl5OFrQMNWfbmCIsjVW-Sn-nQ8


