### Rider Controller Testing

@url = http://localhost:8080/api/ride_on/car

### Testing find all trips from unregistered user's perspective

GET {{url}} HTTP/1.1

### Testing create trip

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer
--- jwt token ---

{
    "tripId": 1
    "departure": "Seattle, WA"
    "arrival": "Atlanta, GA"
    "seats": 7
    "pricePerSeat": 150
    "date": 2023-04-23
    "carId: 1
}